### ISSUE TITLE
after sign in form facebook i got this error 

### ISSUE THREAD

**Issue by aripoya** [AlexanderZaytsev/domp#2]
NoMethodError at /users/auth/facebook/callback

undefined method `create_from_omniauth' for #Class:0xaefd51c

actually i just follow your domp after make rails composer with device included

**Comment by aripoya** [comment]
hi 
sorry that i close that what i opened. after all off Domp needed i heve  installed everything going right way .. still thinking about routing if i use devise + cancan+ active admin + domp

**Comment by batdevis** [comment]
I've the same problem:

undefined method `create_from_omniauth' for #Class:0x00000004112868

in

app/controllers/users/omniauth_callbacks_controller.rb:38:in `create_user_and_authentication_and_sign_in'

**Comment by AlexanderZaytsev** [comment]
@batdevis please upgrade to 0.0.3, should be fixed there.
