### ISSUE TITLE
Seems like an issue when creating the UserAuthentication model 

### ISSUE THREAD

**Issue by YanivRan** [AlexanderZaytsev/domp#8]
In my case instead of:
 attr_accessible :user_id, :authentication_provider_id, :uid, :token, :token_expires_at, :params
It did: 
attr_accessible "#{class_name.downcase}_id", :authentication_provider_id, :uid, :token, :token_expires_at, :params

Seems like an easy enough fix.

**Comment by AlexanderZaytsev** [comment]
Fixed in https://github.com/AlexanderZaytsev/domp/commit/8cfad1484740eadcbf7c7a96b7b697c9d4740c81.

Thanks!
